//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustId { get; set; }
        public string CustCode { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> SrNo { get; set; }
        public string CustName { get; set; }
        public string CtnPer { get; set; }
        public Nullable<int> CtyId { get; set; }
        public Nullable<int> TspId { get; set; }
        public string Address1 { get; set; }
        public string Phone1 { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public string Gender { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
    }
}
