//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Globalconfig
    {
        public int ID { get; set; }
        public string SiteName { get; set; }
        public string SiteMetaDescription { get; set; }
        public string SiteMetaKeywords { get; set; }
        public Nullable<bool> ShowAuthorMetaTag { get; set; }
        public string DatabaseType { get; set; }
        public string DatabaseUsername { get; set; }
        public string DatabaseName { get; set; }
        public Nullable<bool> SendMail { get; set; }
        public string FromEmail { get; set; }
        public string ToEmail { get; set; }
        public string ccToEmail { get; set; }
        public string MailSubjects { get; set; }
        public string MailBody { get; set; }
        public string ToEmailContact { get; set; }
        public string MailSubjectsContact { get; set; }
        public string MailBodyContact { get; set; }
        public string ToEmailSubscribeUser { get; set; }
        public string MailSubjectSubscribe { get; set; }
        public string MailBodySubscribe { get; set; }
        public string ApiKey { get; set; }
        public string ChannelID { get; set; }
        public string OldApiUrl { get; set; }
        public string NewApiUrl { get; set; }
        public string TableBgColor { get; set; }
        public string TableBgTitleColor { get; set; }
        public string DashboardColor { get; set; }
        public string LogoImage { get; set; }
        public string HoverColor { get; set; }
        public string FontColor { get; set; }
        public string LoginBgColor { get; set; }
        public string LoginDescription { get; set; }
        public string LoginLogo { get; set; }
        public Nullable<bool> CheckPermission { get; set; }
    }
}
