//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ipAddressLog
    {
        public System.DateTime last_act { get; set; }
        public string session_id { get; set; }
        public string ip_address { get; set; }
        public string user { get; set; }
    }
}
