//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int ID { get; set; }
        public string MemberCode { get; set; }
        public string MemberName { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<int> TotalPoint { get; set; }
        public Nullable<double> TotalPurchaseAmount { get; set; }
        public string OTPCode { get; set; }
        public Nullable<bool> IsVerify { get; set; }
        public Nullable<bool> IsExchangeMember { get; set; }
    }
}
