//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POSSystemEntities : DbContext
    {
        public POSSystemEntities()
            : base("name=POSSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Coupon> Coupons { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DiscountType> DiscountTypes { get; set; }
        public virtual DbSet<Globalconfig> Globalconfigs { get; set; }
        public virtual DbSet<InvoiceType> InvoiceTypes { get; set; }
        public virtual DbSet<ipAddressLog> ipAddressLogs { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<MediaInfo> MediaInfoes { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<PurchaseDetail> PurchaseDetails { get; set; }
        public virtual DbSet<PurchaseHead> PurchaseHeads { get; set; }
        public virtual DbSet<PurchaseHeader> PurchaseHeaders { get; set; }
        public virtual DbSet<PurchaseItem> PurchaseItems { get; set; }
        public virtual DbSet<ReportMaintenance> ReportMaintenances { get; set; }
        public virtual DbSet<SaleDetail> SaleDetails { get; set; }
        public virtual DbSet<SaleHeader> SaleHeaders { get; set; }
        public virtual DbSet<SalePerson> SalePersons { get; set; }
        public virtual DbSet<SiteInformation> SiteInformations { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<StockClass> StockClasses { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<ThemeSetting> ThemeSettings { get; set; }
        public virtual DbSet<Township> Townships { get; set; }
        public virtual DbSet<TwoFactorData> TwoFactorDatas { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<UserPermission> UserPermissions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<DocumentID> DocumentIDs { get; set; }
    }
}
