//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POSSystemEntities : DbContext
    {
        public POSSystemEntities()
            : base("name=POSSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Coupon> Coupons { get; set; }
        public virtual DbSet<Globalconfig> Globalconfigs { get; set; }
        public virtual DbSet<ipAddressLog> ipAddressLogs { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<PurchaseHead> PurchaseHeads { get; set; }
        public virtual DbSet<PurchaseItem> PurchaseItems { get; set; }
        public virtual DbSet<ReportMaintenance> ReportMaintenances { get; set; }
        public virtual DbSet<SiteInformation> SiteInformations { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TwoFactorData> TwoFactorDatas { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
