//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseItem
    {
        public int ID { get; set; }
        public Nullable<int> HeadID { get; set; }
        public string ItemName { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<double> TotalPrice { get; set; }
    }
}
