//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportMaintenance
    {
        public int ID { get; set; }
        public Nullable<int> SrNo { get; set; }
        public string MainReport { get; set; }
        public string SubReport { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string SubReportKey { get; set; }
    }
}
