//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleHeader
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> CustID { get; set; }
        public Nullable<int> SalesPersonID { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> ServiceCharges { get; set; }
        public Nullable<double> PaidAmount { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<bool> CashDown { get; set; }
        public string Remark { get; set; }
        public Nullable<int> TableID { get; set; }
        public Nullable<bool> Status { get; set; }
        public string CrtUser { get; set; }
        public Nullable<System.DateTime> CrtDate { get; set; }
        public Nullable<System.DateTime> CrtTime { get; set; }
        public string UpdUser { get; set; }
        public Nullable<System.DateTime> UptDate { get; set; }
    }
}
