//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalePerson
    {
        public int ID { get; set; }
        public string SalePersonCode { get; set; }
        public string SalePersonName { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Remarks { get; set; }
    }
}
