//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteInformation
    {
        public int ID { get; set; }
        public string OS { get; set; }
        public string Language { get; set; }
        public string DBName { get; set; }
        public string Users { get; set; }
        public string SiteUrl { get; set; }
        public string FrontSiteUrl { get; set; }
        public Nullable<double> CompMaxFileSize { get; set; }
        public Nullable<double> CompMinFileSize { get; set; }
    }
}
