//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TwoFactorData
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public string User { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> TokenExpired { get; set; }
        public Nullable<bool> TwoFactorEnabled { get; set; }
        public Nullable<bool> TFAEmail { get; set; }
        public Nullable<bool> TFAGoogle { get; set; }
        public string TFAGoogleQRUrl { get; set; }
        public string TFAGoogleCode { get; set; }
        public string GoogleTwoFactorKey { get; set; }
    }
}
