//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string UserCode { get; set; }
        public string UserName { get; set; }
        public string UserName_zhHK { get; set; }
        public string UserName_zhCN { get; set; }
        public string ShortDesc_enUS { get; set; }
        public string ShortDesc_zhHk { get; set; }
        public string ShortDesc_zhCN { get; set; }
        public string Description_enUS { get; set; }
        public string Description_zhHK { get; set; }
        public string Description_zhCN { get; set; }
        public string ImageUrl { get; set; }
        public string DefaultCompany { get; set; }
        public Nullable<int> Password { get; set; }
        public string UserGroupCode { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public int IsLogin { get; set; }
        public Nullable<int> IsLoginLimit { get; set; }
        public Nullable<bool> DeletedStatus { get; set; }
    }
}
