//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroup
    {
        public int ID { get; set; }
        public string GroupCode { get; set; }
        public string GroupName { get; set; }
        public Nullable<bool> DeletedStatus { get; set; }
    }
}
