//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPermission
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> AllowCreateDepartment { get; set; }
        public Nullable<bool> AllowUpdateDepartment { get; set; }
        public Nullable<bool> AllowDeleteDepartment { get; set; }
        public Nullable<bool> AllowCreateCategory { get; set; }
        public Nullable<bool> AllowUpdateCategory { get; set; }
        public Nullable<bool> AllowDeleteCategory { get; set; }
        public Nullable<bool> AllowCreateUser { get; set; }
        public Nullable<bool> AllowUpdateUser { get; set; }
        public Nullable<bool> AllowDeleteUser { get; set; }
        public Nullable<bool> AllowCreateUserGroup { get; set; }
        public Nullable<bool> AllowUpdateUserGroup { get; set; }
        public Nullable<bool> AllowDeleteUserGroup { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
